---
# Install IB web API gateway

- set_fact:
    app_dir: "/opt/ib-gw"

# OS prerequisites
- name: Install prerequisites
  apt:
    pkg:
    - arora # browser
    - default-jre-headless
    - i3
    - i3status
    - j4-dmenu-desktop
    - jq
    - network-manager
    - suckless-tools
    - surf # browser
    - tigervnc-common
    - unzip
    - x11-xserver-utils
    - xss-lock
    - xterm
    update_cache: yes

# Install VNC config
- name: Install VNC config
  copy:
    src: xstartup
    dest: '/home/konrad/.vnc/xstartup'
    owner: konrad
    group: konrad

- name: Touch xresources
  file:
    path: /home/konrad/.Xresources
    state: touch

# Install gateway
- name: Create dir for ib-gw
  file: path="{{ app_dir }}" state=directory
- name: Download ib api gateway
  unarchive:
    src: "https://download2.interactivebrokers.com/portal\
        /clientportal.beta.gw.zip"
    dest: "{{ app_dir }}"
    remote_src: yes

# Run gateway
- name: Check if gateway already running
  shell: pidof java
  register: pidof
  changed_when: false
  failed_when: pidof.stderr != ""
- name: Run ib gateway in background
  shell: ./bin/run.sh root/conf.yaml >> /var/log/ib-gw.log &
  args:
    chdir: "{{ app_dir }}"
  async: 45
  poll: 0
  when: pidof.rc == 1
