---
# Install the IB web API gateway and the fintools-ib app
- hosts: all
  remote_user: root
  tasks:
  - include_role:
      name: install-ib
  - include_role:
      name: install-app
    vars:
      app_name: "{{ APP_NAME | default('fintools-ib') }}"
